// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,js_import_style=module"
// @generated from file proto/silvana/news/v1/news.proto (package silvana.news.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/silvana/news/v1/news.proto.
 */
export const file_proto_silvana_news_v1_news: GenFile = /*@__PURE__*/
  fileDesc("CiBwcm90by9zaWx2YW5hL25ld3MvdjEvbmV3cy5wcm90bxIPc2lsdmFuYS5uZXdzLnYxIi4KBlNvdXJjZRIPCgJpZBgBIAEoCUgAiAEBEgwKBG5hbWUYAiABKAlCBQoDX2lkIq8CCgtOZXdzQXJ0aWNsZRInCgZzb3VyY2UYASABKAsyFy5zaWx2YW5hLm5ld3MudjEuU291cmNlEhMKBmF1dGhvchgCIAEoCUgAiAEBEg0KBXRpdGxlGAMgASgJEhgKC2Rlc2NyaXB0aW9uGAQgASgJSAGIAQESCwoDdXJsGAUgASgJEhkKDHVybF90b19pbWFnZRgGIAEoCUgCiAEBEjAKDHB1Ymxpc2hlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFAoHY29udGVudBgIIAEoCUgDiAEBEhEKCXRleHRfc2l6ZRgJIAEoBUIJCgdfYXV0aG9yQg4KDF9kZXNjcmlwdGlvbkIPCg1fdXJsX3RvX2ltYWdlQgoKCF9jb250ZW50IoABCg5HZXROZXdzUmVxdWVzdBIOCgZ0b2tlbnMYASADKAkSEgoFbGltaXQYAiABKAVIAIgBARIVCghsYW5ndWFnZRgDIAEoCUgBiAEBEhIKBWhvdXJzGAQgASgFSAKIAQFCCAoGX2xpbWl0QgsKCV9sYW5ndWFnZUIICgZfaG91cnMixwEKD0dldE5ld3NSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSLgoKdG9rZW5fbmV3cxgDIAMoCzIaLnNpbHZhbmEubmV3cy52MS5Ub2tlbk5ld3MSEgoKZnJvbV9jYWNoZRgEIAEoCBI5ChBjYWNoZV9leHBpcmVzX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAiAEBQhMKEV9jYWNoZV9leHBpcmVzX2F0IqABCglUb2tlbk5ld3MSDQoFdG9rZW4YASABKAkSDQoFcXVlcnkYAiABKAkSFQoNdG90YWxfcmVzdWx0cxgDIAEoBRIuCghhcnRpY2xlcxgEIAMoCzIcLnNpbHZhbmEubmV3cy52MS5OZXdzQXJ0aWNsZRIuCgpmZXRjaGVkX2F0GAUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJVChFTdHJlYW1OZXdzUmVxdWVzdBIOCgZ0b2tlbnMYASADKAkSHAoPdXBkYXRlX2ludGVydmFsGAIgASgFSACIAQFCEgoQX3VwZGF0ZV9pbnRlcnZhbDKtAQoLTmV3c1NlcnZpY2USTAoHR2V0TmV3cxIfLnNpbHZhbmEubmV3cy52MS5HZXROZXdzUmVxdWVzdBogLnNpbHZhbmEubmV3cy52MS5HZXROZXdzUmVzcG9uc2USUAoKU3RyZWFtTmV3cxIiLnNpbHZhbmEubmV3cy52MS5TdHJlYW1OZXdzUmVxdWVzdBocLnNpbHZhbmEubmV3cy52MS5OZXdzQXJ0aWNsZTABQi9aLWdpdGh1Yi5jb20vU2lsdmFuYU9uZS9jYW50b24tYWdlbnQvcHJvdG87bmV3c2IGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * News article source information
 *
 * @generated from message silvana.news.v1.Source
 */
export type Source = Message<"silvana.news.v1.Source"> & {
  /**
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message silvana.news.v1.Source.
 * Use `create(SourceSchema)` to create a new message.
 */
export const SourceSchema: GenMessage<Source> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 0);

/**
 * News article
 *
 * @generated from message silvana.news.v1.NewsArticle
 */
export type NewsArticle = Message<"silvana.news.v1.NewsArticle"> & {
  /**
   * @generated from field: silvana.news.v1.Source source = 1;
   */
  source?: Source;

  /**
   * @generated from field: optional string author = 2;
   */
  author?: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: string url = 5;
   */
  url: string;

  /**
   * @generated from field: optional string url_to_image = 6;
   */
  urlToImage?: string;

  /**
   * @generated from field: google.protobuf.Timestamp published_at = 7;
   */
  publishedAt?: Timestamp;

  /**
   * @generated from field: optional string content = 8;
   */
  content?: string;

  /**
   * Total text size (title + description + content)
   *
   * @generated from field: int32 text_size = 9;
   */
  textSize: number;
};

/**
 * Describes the message silvana.news.v1.NewsArticle.
 * Use `create(NewsArticleSchema)` to create a new message.
 */
export const NewsArticleSchema: GenMessage<NewsArticle> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 1);

/**
 * Request for news articles
 *
 * @generated from message silvana.news.v1.GetNewsRequest
 */
export type GetNewsRequest = Message<"silvana.news.v1.GetNewsRequest"> & {
  /**
   * Cryptocurrency tokens to fetch news for (e.g., "btc", "eth", "mina")
   * If empty, fetches news for default tokens (btc, eth, mina)
   *
   * @generated from field: repeated string tokens = 1;
   */
  tokens: string[];

  /**
   * Maximum number of articles per token
   *
   * Default: 5
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number;

  /**
   * Filter by language (e.g., "en")
   *
   * Default: "en"
   *
   * @generated from field: optional string language = 3;
   */
  language?: string;

  /**
   * Time window in hours (e.g., 48 for last 48 hours)
   *
   * Default: 48
   *
   * @generated from field: optional int32 hours = 4;
   */
  hours?: number;
};

/**
 * Describes the message silvana.news.v1.GetNewsRequest.
 * Use `create(GetNewsRequestSchema)` to create a new message.
 */
export const GetNewsRequestSchema: GenMessage<GetNewsRequest> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 2);

/**
 * Response containing news articles
 *
 * @generated from message silvana.news.v1.GetNewsResponse
 */
export type GetNewsResponse = Message<"silvana.news.v1.GetNewsResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * News results grouped by token
   *
   * @generated from field: repeated silvana.news.v1.TokenNews token_news = 3;
   */
  tokenNews: TokenNews[];

  /**
   * Indicates if results were served from cache
   *
   * @generated from field: bool from_cache = 4;
   */
  fromCache: boolean;

  /**
   * Cache expiration time (if from_cache = true)
   *
   * @generated from field: optional google.protobuf.Timestamp cache_expires_at = 5;
   */
  cacheExpiresAt?: Timestamp;
};

/**
 * Describes the message silvana.news.v1.GetNewsResponse.
 * Use `create(GetNewsResponseSchema)` to create a new message.
 */
export const GetNewsResponseSchema: GenMessage<GetNewsResponse> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 3);

/**
 * News articles for a specific token
 *
 * @generated from message silvana.news.v1.TokenNews
 */
export type TokenNews = Message<"silvana.news.v1.TokenNews"> & {
  /**
   * e.g., "btc", "eth", "mina"
   *
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * Search query used (e.g., "bitcoin", "ethereum")
   *
   * @generated from field: string query = 2;
   */
  query: string;

  /**
   * @generated from field: int32 total_results = 3;
   */
  totalResults: number;

  /**
   * @generated from field: repeated silvana.news.v1.NewsArticle articles = 4;
   */
  articles: NewsArticle[];

  /**
   * @generated from field: google.protobuf.Timestamp fetched_at = 5;
   */
  fetchedAt?: Timestamp;
};

/**
 * Describes the message silvana.news.v1.TokenNews.
 * Use `create(TokenNewsSchema)` to create a new message.
 */
export const TokenNewsSchema: GenMessage<TokenNews> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 4);

/**
 * Request for streaming news updates
 *
 * @generated from message silvana.news.v1.StreamNewsRequest
 */
export type StreamNewsRequest = Message<"silvana.news.v1.StreamNewsRequest"> & {
  /**
   * Cryptocurrency tokens to stream news for
   *
   * @generated from field: repeated string tokens = 1;
   */
  tokens: string[];

  /**
   * Minimum time between updates in seconds
   *
   * Default: 300 (5 minutes)
   *
   * @generated from field: optional int32 update_interval = 2;
   */
  updateInterval?: number;
};

/**
 * Describes the message silvana.news.v1.StreamNewsRequest.
 * Use `create(StreamNewsRequestSchema)` to create a new message.
 */
export const StreamNewsRequestSchema: GenMessage<StreamNewsRequest> = /*@__PURE__*/
  messageDesc(file_proto_silvana_news_v1_news, 5);

/**
 * @generated from service silvana.news.v1.NewsService
 */
export const NewsService: GenService<{
  /**
   * Get news articles for specific cryptocurrencies
   *
   * @generated from rpc silvana.news.v1.NewsService.GetNews
   */
  getNews: {
    methodKind: "unary";
    input: typeof GetNewsRequestSchema;
    output: typeof GetNewsResponseSchema;
  },
  /**
   * Stream real-time news updates (optional future enhancement)
   *
   * @generated from rpc silvana.news.v1.NewsService.StreamNews
   */
  streamNews: {
    methodKind: "server_streaming";
    input: typeof StreamNewsRequestSchema;
    output: typeof NewsArticleSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_silvana_news_v1_news, 0);

