// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/cip56.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/cip56.proto.
 */
export const file_silvana_ledger_v1_cip56: GenFile = /*@__PURE__*/
  fileDesc("Ch1zaWx2YW5hL2xlZGdlci92MS9jaXA1Ni5wcm90bxIRc2lsdmFuYS5sZWRnZXIudjEilAEKE1RyYW5zZmVyQ2lwNTZQYXJhbXMSFQoNaW5zdHJ1bWVudF9pZBgBIAEoCRIYChBpbnN0cnVtZW50X2FkbWluGAIgASgJEhYKDnJlY2VpdmVyX3BhcnR5GAMgASgJEg4KBmFtb3VudBgEIAEoCRIWCglyZWZlcmVuY2UYBSABKAlIAIgBAUIMCgpfcmVmZXJlbmNlIigKEUFjY2VwdENpcDU2UGFyYW1zEhMKC2NvbnRyYWN0X2lkGAEgASgJQjFaL2dpdGh1Yi5jb20vU2lsdmFuYU9uZS9jYW50b24tYWdlbnQvcHJvdG87bGVkZ2VyYgZwcm90bzM");

/**
 * CIP-56 instrument transfer — fully qualified instrument required
 * Daml InstrumentId = { id: Text, admin: Party }
 *
 * @generated from message silvana.ledger.v1.TransferCip56Params
 */
export type TransferCip56Params = Message<"silvana.ledger.v1.TransferCip56Params"> & {
  /**
   * Token name, e.g. "USDC", "CBTC"
   *
   * @generated from field: string instrument_id = 1;
   */
  instrumentId: string;

  /**
   * Registrar party (InstrumentId.admin / instrument source)
   *
   * @generated from field: string instrument_admin = 2;
   */
  instrumentAdmin: string;

  /**
   * Full Canton party ID of receiver
   *
   * @generated from field: string receiver_party = 3;
   */
  receiverParty: string;

  /**
   * Decimal string
   *
   * @generated from field: string amount = 4;
   */
  amount: string;

  /**
   * Optional transfer reference/description
   *
   * @generated from field: optional string reference = 5;
   */
  reference?: string | undefined;
};

/**
 * Describes the message silvana.ledger.v1.TransferCip56Params.
 * Use `create(TransferCip56ParamsSchema)` to create a new message.
 */
export const TransferCip56ParamsSchema: GenMessage<TransferCip56Params> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_cip56, 0);

/**
 * Accept incoming CIP-56 TransferOffer — registrar extracted from contract payload
 *
 * @generated from message silvana.ledger.v1.AcceptCip56Params
 */
export type AcceptCip56Params = Message<"silvana.ledger.v1.AcceptCip56Params"> & {
  /**
   * TransferOffer contract ID to accept
   *
   * @generated from field: string contract_id = 1;
   */
  contractId: string;
};

/**
 * Describes the message silvana.ledger.v1.AcceptCip56Params.
 * Use `create(AcceptCip56ParamsSchema)` to create a new message.
 */
export const AcceptCip56ParamsSchema: GenMessage<AcceptCip56Params> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_cip56, 1);

