// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/dvp.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/dvp.proto.
 */
export const file_silvana_ledger_v1_dvp: GenFile = /*@__PURE__*/
  fileDesc("ChtzaWx2YW5hL2xlZGdlci92MS9kdnAucHJvdG8SEXNpbHZhbmEubGVkZ2VyLnYxIjcKHUdldFNldHRsZW1lbnRDb250cmFjdHNSZXF1ZXN0EhYKDnNldHRsZW1lbnRfaWRzGAEgAygJIlcKEkRpc2NvdmVyZWRDb250cmFjdBIVCg1zZXR0bGVtZW50X2lkGAEgASgJEhMKC2NvbnRyYWN0X2lkGAIgASgJEhUKDWNvbnRyYWN0X3R5cGUYAyABKAkiWgoeR2V0U2V0dGxlbWVudENvbnRyYWN0c1Jlc3BvbnNlEjgKCWNvbnRyYWN0cxgBIAMoCzIlLnNpbHZhbmEubGVkZ2VyLnYxLkRpc2NvdmVyZWRDb250cmFjdCJKCgxQYXlGZWVQYXJhbXMSEwoLcHJvcG9zYWxfaWQYASABKAkSEAoIZmVlX3R5cGUYAiABKAkSEwoLYW11bGV0X2NpZHMYAyADKAkiJwoQUHJvcG9zZUR2cFBhcmFtcxITCgtwcm9wb3NhbF9pZBgBIAEoCSJACg9BY2NlcHREdnBQYXJhbXMSEwoLcHJvcG9zYWxfaWQYASABKAkSGAoQZHZwX3Byb3Bvc2FsX2NpZBgCIAEoCSJLCg5BbGxvY2F0ZVBhcmFtcxITCgtwcm9wb3NhbF9pZBgBIAEoCRIPCgdkdnBfY2lkGAIgASgJEhMKC2FtdWxldF9jaWRzGAMgAygJQjFaL2dpdGh1Yi5jb20vU2lsdmFuYU9uZS9jYW50b24tYWdlbnQvcHJvdG87bGVkZ2VyYgZwcm90bzM");

/**
 * @generated from message silvana.ledger.v1.GetSettlementContractsRequest
 */
export type GetSettlementContractsRequest = Message<"silvana.ledger.v1.GetSettlementContractsRequest"> & {
  /**
   * proposal/settlement IDs to search for
   *
   * @generated from field: repeated string settlement_ids = 1;
   */
  settlementIds: string[];
};

/**
 * Describes the message silvana.ledger.v1.GetSettlementContractsRequest.
 * Use `create(GetSettlementContractsRequestSchema)` to create a new message.
 */
export const GetSettlementContractsRequestSchema: GenMessage<GetSettlementContractsRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 0);

/**
 * @generated from message silvana.ledger.v1.DiscoveredContract
 */
export type DiscoveredContract = Message<"silvana.ledger.v1.DiscoveredContract"> & {
  /**
   * @generated from field: string settlement_id = 1;
   */
  settlementId: string;

  /**
   * @generated from field: string contract_id = 2;
   */
  contractId: string;

  /**
   * "DvpProposal" or "Dvp"
   *
   * @generated from field: string contract_type = 3;
   */
  contractType: string;
};

/**
 * Describes the message silvana.ledger.v1.DiscoveredContract.
 * Use `create(DiscoveredContractSchema)` to create a new message.
 */
export const DiscoveredContractSchema: GenMessage<DiscoveredContract> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 1);

/**
 * @generated from message silvana.ledger.v1.GetSettlementContractsResponse
 */
export type GetSettlementContractsResponse = Message<"silvana.ledger.v1.GetSettlementContractsResponse"> & {
  /**
   * @generated from field: repeated silvana.ledger.v1.DiscoveredContract contracts = 1;
   */
  contracts: DiscoveredContract[];
};

/**
 * Describes the message silvana.ledger.v1.GetSettlementContractsResponse.
 * Use `create(GetSettlementContractsResponseSchema)` to create a new message.
 */
export const GetSettlementContractsResponseSchema: GenMessage<GetSettlementContractsResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 2);

/**
 * @generated from message silvana.ledger.v1.PayFeeParams
 */
export type PayFeeParams = Message<"silvana.ledger.v1.PayFeeParams"> & {
  /**
   * @generated from field: string proposal_id = 1;
   */
  proposalId: string;

  /**
   * "dvp" or "allocate"
   *
   * @generated from field: string fee_type = 2;
   */
  feeType: string;

  /**
   * Pre-selected amulet contract IDs (empty = server selects)
   *
   * @generated from field: repeated string amulet_cids = 3;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.PayFeeParams.
 * Use `create(PayFeeParamsSchema)` to create a new message.
 */
export const PayFeeParamsSchema: GenMessage<PayFeeParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 3);

/**
 * @generated from message silvana.ledger.v1.ProposeDvpParams
 */
export type ProposeDvpParams = Message<"silvana.ledger.v1.ProposeDvpParams"> & {
  /**
   * @generated from field: string proposal_id = 1;
   */
  proposalId: string;
};

/**
 * Describes the message silvana.ledger.v1.ProposeDvpParams.
 * Use `create(ProposeDvpParamsSchema)` to create a new message.
 */
export const ProposeDvpParamsSchema: GenMessage<ProposeDvpParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 4);

/**
 * @generated from message silvana.ledger.v1.AcceptDvpParams
 */
export type AcceptDvpParams = Message<"silvana.ledger.v1.AcceptDvpParams"> & {
  /**
   * @generated from field: string proposal_id = 1;
   */
  proposalId: string;

  /**
   * @generated from field: string dvp_proposal_cid = 2;
   */
  dvpProposalCid: string;
};

/**
 * Describes the message silvana.ledger.v1.AcceptDvpParams.
 * Use `create(AcceptDvpParamsSchema)` to create a new message.
 */
export const AcceptDvpParamsSchema: GenMessage<AcceptDvpParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 5);

/**
 * @generated from message silvana.ledger.v1.AllocateParams
 */
export type AllocateParams = Message<"silvana.ledger.v1.AllocateParams"> & {
  /**
   * @generated from field: string proposal_id = 1;
   */
  proposalId: string;

  /**
   * @generated from field: string dvp_cid = 2;
   */
  dvpCid: string;

  /**
   * Pre-selected amulet contract IDs (empty = server selects)
   *
   * @generated from field: repeated string amulet_cids = 3;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.AllocateParams.
 * Use `create(AllocateParamsSchema)` to create a new message.
 */
export const AllocateParamsSchema: GenMessage<AllocateParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_dvp, 6);

