// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/faucet.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MessageSignature } from "./common_pb.js";
import { file_silvana_ledger_v1_common } from "./common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/faucet.proto.
 */
export const file_silvana_ledger_v1_faucet: GenFile = /*@__PURE__*/
  fileDesc("Ch5zaWx2YW5hL2xlZGdlci92MS9mYXVjZXQucHJvdG8SEXNpbHZhbmEubGVkZ2VyLnYxIqkBCg1GYXVjZXRSZXF1ZXN0EhIKCnRva2VuX25hbWUYASABKAkSEwoLdG9rZW5fYWRtaW4YAiABKAkSDgoGdGlja2V0GAMgASgJEg4KBmFtb3VudBgEIAEoCRIPCgdkcnlfcnVuGAUgASgIEj4KEXJlcXVlc3Rfc2lnbmF0dXJlGB4gASgLMiMuc2lsdmFuYS5sZWRnZXIudjEuTWVzc2FnZVNpZ25hdHVyZSL5AQoORmF1Y2V0UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIRCgl1cGRhdGVfaWQYAiABKAkSGgoNZXJyb3JfbWVzc2FnZRgDIAEoCUgAiAEBEhcKD2Ftb3VudF9hcHByb3ZlZBgEIAEoCRISCgp0b2tlbl9uYW1lGAUgASgJEhMKC3Rva2VuX2FkbWluGAYgASgJEhIKCmlzX2RyeV9ydW4YByABKAgSPwoScmVzcG9uc2Vfc2lnbmF0dXJlGB4gASgLMiMuc2lsdmFuYS5sZWRnZXIudjEuTWVzc2FnZVNpZ25hdHVyZUIQCg5fZXJyb3JfbWVzc2FnZUIxWi9naXRodWIuY29tL1NpbHZhbmFPbmUvY2FudG9uLWFnZW50L3Byb3RvO2xlZGdlcmIGcHJvdG8z", [file_silvana_ledger_v1_common]);

/**
 * @generated from message silvana.ledger.v1.FaucetRequest
 */
export type FaucetRequest = Message<"silvana.ledger.v1.FaucetRequest"> & {
  /**
   * "Amulet" (CC), "USDC", "HECTO", etc.
   *
   * @generated from field: string token_name = 1;
   */
  tokenName: string;

  /**
   * DSO party for CC, registrar party for CIP-56
   *
   * @generated from field: string token_admin = 2;
   */
  tokenAdmin: string;

  /**
   * Validation ticket (devnet: any string; mainnet: base64 x402 X-PAYMENT)
   *
   * @generated from field: string ticket = 3;
   */
  ticket: string;

  /**
   * Requested amount (empty = use default from configuration.toml)
   *
   * @generated from field: string amount = 4;
   */
  amount: string;

  /**
   * If true, validate ticket and return approval info without executing
   *
   * @generated from field: bool dry_run = 5;
   */
  dryRun: boolean;

  /**
   * Message-level signature from cloud agent (Ed25519 over canonical request payload)
   *
   * @generated from field: silvana.ledger.v1.MessageSignature request_signature = 30;
   */
  requestSignature?: MessageSignature;
};

/**
 * Describes the message silvana.ledger.v1.FaucetRequest.
 * Use `create(FaucetRequestSchema)` to create a new message.
 */
export const FaucetRequestSchema: GenMessage<FaucetRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_faucet, 0);

/**
 * @generated from message silvana.ledger.v1.FaucetResponse
 */
export type FaucetResponse = Message<"silvana.ledger.v1.FaucetResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * Canton update ID (empty if dry_run=true)
   *
   * @generated from field: string update_id = 2;
   */
  updateId: string;

  /**
   * @generated from field: optional string error_message = 3;
   */
  errorMessage?: string;

  /**
   * Amount that would be / was sent
   *
   * @generated from field: string amount_approved = 4;
   */
  amountApproved: string;

  /**
   * Confirmed token name
   *
   * @generated from field: string token_name = 5;
   */
  tokenName: string;

  /**
   * Confirmed admin party
   *
   * @generated from field: string token_admin = 6;
   */
  tokenAdmin: string;

  /**
   * Echo back dry_run flag
   *
   * @generated from field: bool is_dry_run = 7;
   */
  isDryRun: boolean;

  /**
   * Message-level signature from dApp provider service
   *
   * @generated from field: silvana.ledger.v1.MessageSignature response_signature = 30;
   */
  responseSignature?: MessageSignature;
};

/**
 * Describes the message silvana.ledger.v1.FaucetResponse.
 * Use `create(FaucetResponseSchema)` to create a new message.
 */
export const FaucetResponseSchema: GenMessage<FaucetResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_faucet, 1);

