// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/fees.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/fees.proto.
 */
export const file_silvana_ledger_v1_fees: GenFile = /*@__PURE__*/
  fileDesc("ChxzaWx2YW5hL2xlZGdlci92MS9mZWVzLnByb3RvEhFzaWx2YW5hLmxlZGdlci52MSJBCgNGZWUSEgoKZW50cnlfdHlwZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCRIRCglhbW91bnRfY2MYAyABKAlCMVovZ2l0aHViLmNvbS9TaWx2YW5hT25lL2NhbnRvbi1hZ2VudC9wcm90bztsZWRnZXJiBnByb3RvMw");

/**
 * @generated from message silvana.ledger.v1.Fee
 */
export type Fee = Message<"silvana.ledger.v1.Fee"> & {
  /**
   * free-form category
   *
   * @generated from field: string entry_type = 1;
   */
  entryType: string;

  /**
   * human-readable
   *
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * decimal string
   *
   * @generated from field: string amount_cc = 3;
   */
  amountCc: string;
};

/**
 * Describes the message silvana.ledger.v1.Fee.
 * Use `create(FeeSchema)` to create a new message.
 */
export const FeeSchema: GenMessage<Fee> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_fees, 0);

