// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/lock.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/lock.proto.
 */
export const file_silvana_ledger_v1_lock: GenFile = /*@__PURE__*/
  fileDesc("ChxzaWx2YW5hL2xlZGdlci92MS9sb2NrLnByb3RvEhFzaWx2YW5hLmxlZGdlci52MSIzChBWb3RpbmdBbGxvY2F0aW9uEg8KB2NvbnRleHQYASABKAkSDgoGYW1vdW50GAIgASgJIkMKDVZvdGluZ1JlcXVlc3QSDwoHY29udGV4dBgBIAEoCRIOCgZhbW91bnQYAiABKAkSEQoJZGlyZWN0aW9uGAMgASgJIp4CChJMb2NrSG9sZGluZ3NQYXJhbXMSGAoQbG9ja19zZXJ2aWNlX2NpZBgBIAEoCRIgChhsb2NrX3NlcnZpY2VfdGVtcGxhdGVfaWQYAiABKAkSGQoRbG9ja19zZXJ2aWNlX2Jsb2IYAyABKAkSDgoGYW1vdW50GAQgASgJEhUKDWluc3RydW1lbnRfaWQYBSABKAkSDwoHY29udGV4dBgGIAEoCRI4CgthbGxvY2F0aW9ucxgHIAMoCzIjLnNpbHZhbmEubGVkZ2VyLnYxLlZvdGluZ0FsbG9jYXRpb24SFQoNZmVlX3BhcnR5X2lkcxgKIAMoCRITCgtmZWVfYW1vdW50cxgLIAMoCRITCgthbXVsZXRfY2lkcxgMIAMoCSLYAQofUHJvY2Vzc0xvY2tVbmxvY2tSZXF1ZXN0c1BhcmFtcxIbChNsb2NrX2NvbnRyb2xsZXJfY2lkGAEgASgJEiMKG2xvY2tfY29udHJvbGxlcl90ZW1wbGF0ZV9pZBgCIAEoCRIyCghyZXF1ZXN0cxgDIAMoCzIgLnNpbHZhbmEubGVkZ2VyLnYxLlZvdGluZ1JlcXVlc3QSFQoNZmVlX3BhcnR5X2lkcxgKIAMoCRITCgtmZWVfYW1vdW50cxgLIAMoCRITCgthbXVsZXRfY2lkcxgMIAMoCSL0AQoQUmVzaXplTG9ja1BhcmFtcxIbChNsb2NrX2NvbnRyb2xsZXJfY2lkGAEgASgJEiMKG2xvY2tfY29udHJvbGxlcl90ZW1wbGF0ZV9pZBgCIAEoCRISCgpuZXdfYW1vdW50GAMgASgJEjIKCHJlcXVlc3RzGAQgAygLMiAuc2lsdmFuYS5sZWRnZXIudjEuVm90aW5nUmVxdWVzdBIVCg1pbnN0cnVtZW50X2lkGAUgASgJEhUKDWZlZV9wYXJ0eV9pZHMYCiADKAkSEwoLZmVlX2Ftb3VudHMYCyADKAkSEwoLYW11bGV0X2NpZHMYDCADKAkimAEKE1Rlcm1pbmF0ZUxvY2tQYXJhbXMSGwoTbG9ja19jb250cm9sbGVyX2NpZBgBIAEoCRIjChtsb2NrX2NvbnRyb2xsZXJfdGVtcGxhdGVfaWQYAiABKAkSFQoNZmVlX3BhcnR5X2lkcxgKIAMoCRITCgtmZWVfYW1vdW50cxgLIAMoCRITCgthbXVsZXRfY2lkcxgMIAMoCUIxWi9naXRodWIuY29tL1NpbHZhbmFPbmUvY2FudG9uLWFnZW50L3Byb3RvO2xlZGdlcmIGcHJvdG8z");

/**
 * Voting allocation for lock context
 *
 * @generated from message silvana.ledger.v1.VotingAllocation
 */
export type VotingAllocation = Message<"silvana.ledger.v1.VotingAllocation"> & {
  /**
   * UUID identifying the allocation target
   *
   * @generated from field: string context = 1;
   */
  context: string;

  /**
   * Decimal amount allocated
   *
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message silvana.ledger.v1.VotingAllocation.
 * Use `create(VotingAllocationSchema)` to create a new message.
 */
export const VotingAllocationSchema: GenMessage<VotingAllocation> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 0);

/**
 * Voting request (lock or unlock direction)
 *
 * @generated from message silvana.ledger.v1.VotingRequest
 */
export type VotingRequest = Message<"silvana.ledger.v1.VotingRequest"> & {
  /**
   * UUID identifying the allocation target
   *
   * @generated from field: string context = 1;
   */
  context: string;

  /**
   * Decimal amount to lock/unlock
   *
   * @generated from field: string amount = 2;
   */
  amount: string;

  /**
   * "VoteLock" or "VoteUnlock"
   *
   * @generated from field: string direction = 3;
   */
  direction: string;
};

/**
 * Describes the message silvana.ledger.v1.VotingRequest.
 * Use `create(VotingRequestSchema)` to create a new message.
 */
export const VotingRequestSchema: GenMessage<VotingRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 1);

/**
 * @generated from message silvana.ledger.v1.LockHoldingsParams
 */
export type LockHoldingsParams = Message<"silvana.ledger.v1.LockHoldingsParams"> & {
  /**
   * LockService contract ID
   *
   * @generated from field: string lock_service_cid = 1;
   */
  lockServiceCid: string;

  /**
   * LockService template ID
   *
   * @generated from field: string lock_service_template_id = 2;
   */
  lockServiceTemplateId: string;

  /**
   * LockService created_event_blob (for disclosure)
   *
   * @generated from field: string lock_service_blob = 3;
   */
  lockServiceBlob: string;

  /**
   * Amount to lock
   *
   * @generated from field: string amount = 4;
   */
  amount: string;

  /**
   * Instrument token ID (e.g., "HECTO")
   *
   * @generated from field: string instrument_id = 5;
   */
  instrumentId: string;

  /**
   * Lock context (UUIDv7; server generates if empty)
   *
   * @generated from field: string context = 6;
   */
  context: string;

  /**
   * @generated from field: repeated silvana.ledger.v1.VotingAllocation allocations = 7;
   */
  allocations: VotingAllocation[];

  /**
   * Fee payment (optional)
   *
   * @generated from field: repeated string fee_party_ids = 10;
   */
  feePartyIds: string[];

  /**
   * @generated from field: repeated string fee_amounts = 11;
   */
  feeAmounts: string[];

  /**
   * Amulets for fee payment
   *
   * @generated from field: repeated string amulet_cids = 12;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.LockHoldingsParams.
 * Use `create(LockHoldingsParamsSchema)` to create a new message.
 */
export const LockHoldingsParamsSchema: GenMessage<LockHoldingsParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 2);

/**
 * @generated from message silvana.ledger.v1.ProcessLockUnlockRequestsParams
 */
export type ProcessLockUnlockRequestsParams = Message<"silvana.ledger.v1.ProcessLockUnlockRequestsParams"> & {
  /**
   * @generated from field: string lock_controller_cid = 1;
   */
  lockControllerCid: string;

  /**
   * @generated from field: string lock_controller_template_id = 2;
   */
  lockControllerTemplateId: string;

  /**
   * @generated from field: repeated silvana.ledger.v1.VotingRequest requests = 3;
   */
  requests: VotingRequest[];

  /**
   * Fee payment (optional)
   *
   * @generated from field: repeated string fee_party_ids = 10;
   */
  feePartyIds: string[];

  /**
   * @generated from field: repeated string fee_amounts = 11;
   */
  feeAmounts: string[];

  /**
   * @generated from field: repeated string amulet_cids = 12;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.ProcessLockUnlockRequestsParams.
 * Use `create(ProcessLockUnlockRequestsParamsSchema)` to create a new message.
 */
export const ProcessLockUnlockRequestsParamsSchema: GenMessage<ProcessLockUnlockRequestsParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 3);

/**
 * @generated from message silvana.ledger.v1.ResizeLockParams
 */
export type ResizeLockParams = Message<"silvana.ledger.v1.ResizeLockParams"> & {
  /**
   * @generated from field: string lock_controller_cid = 1;
   */
  lockControllerCid: string;

  /**
   * @generated from field: string lock_controller_template_id = 2;
   */
  lockControllerTemplateId: string;

  /**
   * @generated from field: string new_amount = 3;
   */
  newAmount: string;

  /**
   * @generated from field: repeated silvana.ledger.v1.VotingRequest requests = 4;
   */
  requests: VotingRequest[];

  /**
   * Instrument token ID (for querying additional holdings)
   *
   * @generated from field: string instrument_id = 5;
   */
  instrumentId: string;

  /**
   * Fee payment (optional)
   *
   * @generated from field: repeated string fee_party_ids = 10;
   */
  feePartyIds: string[];

  /**
   * @generated from field: repeated string fee_amounts = 11;
   */
  feeAmounts: string[];

  /**
   * @generated from field: repeated string amulet_cids = 12;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.ResizeLockParams.
 * Use `create(ResizeLockParamsSchema)` to create a new message.
 */
export const ResizeLockParamsSchema: GenMessage<ResizeLockParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 4);

/**
 * @generated from message silvana.ledger.v1.TerminateLockParams
 */
export type TerminateLockParams = Message<"silvana.ledger.v1.TerminateLockParams"> & {
  /**
   * @generated from field: string lock_controller_cid = 1;
   */
  lockControllerCid: string;

  /**
   * @generated from field: string lock_controller_template_id = 2;
   */
  lockControllerTemplateId: string;

  /**
   * Fee payment (optional)
   *
   * @generated from field: repeated string fee_party_ids = 10;
   */
  feePartyIds: string[];

  /**
   * @generated from field: repeated string fee_amounts = 11;
   */
  feeAmounts: string[];

  /**
   * @generated from field: repeated string amulet_cids = 12;
   */
  amuletCids: string[];
};

/**
 * Describes the message silvana.ledger.v1.TerminateLockParams.
 * Use `create(TerminateLockParamsSchema)` to create a new message.
 */
export const TerminateLockParamsSchema: GenMessage<TerminateLockParams> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_lock, 5);

