// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,js_import_style=module,import_extension=.js"
// @generated from file silvana/ledger/v1/onboarding.proto (package silvana.ledger.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MessageSignature } from "./common_pb.js";
import { file_silvana_ledger_v1_common } from "./common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file silvana/ledger/v1/onboarding.proto.
 */
export const file_silvana_ledger_v1_onboarding: GenFile = /*@__PURE__*/
  fileDesc("CiJzaWx2YW5hL2xlZGdlci92MS9vbmJvYXJkaW5nLnByb3RvEhFzaWx2YW5hLmxlZGdlci52MSIXChVHZXRBZ2VudENvbmZpZ1JlcXVlc3QiOQoWR2V0QWdlbnRDb25maWdSZXNwb25zZRILCgNlbnYYASABKAkSEgoKYWdlbnRfdG9tbBgCIAEoCSLaAQoUUmVnaXN0ZXJBZ2VudFJlcXVlc3QSEgoKcHVibGljX2tleRgBIAEoCRIYCgtpbnZpdGVfY29kZRgCIAEoCUgAiAEBEhIKBWVtYWlsGAMgASgJSAGIAQESFwoKYWdlbnRfbmFtZRgEIAEoCUgCiAEBEj4KEXJlcXVlc3Rfc2lnbmF0dXJlGB4gASgLMiMuc2lsdmFuYS5sZWRnZXIudjEuTWVzc2FnZVNpZ25hdHVyZUIOCgxfaW52aXRlX2NvZGVCCAoGX2VtYWlsQg0KC19hZ2VudF9uYW1lIocBChVSZWdpc3RlckFnZW50UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIPCgdtZXNzYWdlGAIgASgJEhcKD3dhaXRpbmdfbGlzdF9pZBgDIAEoBBIzCgZzdGF0dXMYBCABKA4yIy5zaWx2YW5hLmxlZGdlci52MS5PbmJvYXJkaW5nU3RhdHVzInAKGkdldE9uYm9hcmRpbmdTdGF0dXNSZXF1ZXN0EhIKCnB1YmxpY19rZXkYASABKAkSPgoRcmVxdWVzdF9zaWduYXR1cmUYHiABKAsyIy5zaWx2YW5hLmxlZGdlci52MS5NZXNzYWdlU2lnbmF0dXJlIuMBChtHZXRPbmJvYXJkaW5nU3RhdHVzUmVzcG9uc2USMwoGc3RhdHVzGAEgASgOMiMuc2lsdmFuYS5sZWRnZXIudjEuT25ib2FyZGluZ1N0YXR1cxIVCghwYXJ0eV9pZBgCIAEoCUgAiAEBEhYKCW11bHRpaGFzaBgDIAEoCUgBiAEBEhoKDWVycm9yX21lc3NhZ2UYBCABKAlIAogBARIXCg93YWl0aW5nX2xpc3RfaWQYBSABKARCCwoJX3BhcnR5X2lkQgwKCl9tdWx0aWhhc2hCEAoOX2Vycm9yX21lc3NhZ2UikwEKIFN1Ym1pdE9uYm9hcmRpbmdTaWduYXR1cmVSZXF1ZXN0EhIKCnB1YmxpY19rZXkYASABKAkSGwoTbXVsdGloYXNoX3NpZ25hdHVyZRgCIAEoCRI+ChFyZXF1ZXN0X3NpZ25hdHVyZRgeIAEoCzIjLnNpbHZhbmEubGVkZ2VyLnYxLk1lc3NhZ2VTaWduYXR1cmUiegohU3VibWl0T25ib2FyZGluZ1NpZ25hdHVyZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCRIzCgZzdGF0dXMYAyABKA4yIy5zaWx2YW5hLmxlZGdlci52MS5PbmJvYXJkaW5nU3RhdHVzKskBChBPbmJvYXJkaW5nU3RhdHVzEiEKHU9OQk9BUkRJTkdfU1RBVFVTX1VOU1BFQ0lGSUVEEAASHwobT05CT0FSRElOR19TVEFUVVNfUkVRVUVTVEVEEAESKAokT05CT0FSRElOR19TVEFUVVNfU0lHTkFUVVJFX1JFUVVJUkVEEAISJgoiT05CT0FSRElOR19TVEFUVVNfVE9QT0xPR1lfQ1JFQVRFRBADEh8KG09OQk9BUkRJTkdfU1RBVFVTX09OQk9BUkRFRBAEQjFaL2dpdGh1Yi5jb20vU2lsdmFuYU9uZS9jYW50b24tYWdlbnQvcHJvdG87bGVkZ2VyYgZwcm90bzM", [file_silvana_ledger_v1_common]);

/**
 * @generated from message silvana.ledger.v1.GetAgentConfigRequest
 */
export type GetAgentConfigRequest = Message<"silvana.ledger.v1.GetAgentConfigRequest"> & {
};

/**
 * Describes the message silvana.ledger.v1.GetAgentConfigRequest.
 * Use `create(GetAgentConfigRequestSchema)` to create a new message.
 */
export const GetAgentConfigRequestSchema: GenMessage<GetAgentConfigRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 0);

/**
 * @generated from message silvana.ledger.v1.GetAgentConfigResponse
 */
export type GetAgentConfigResponse = Message<"silvana.ledger.v1.GetAgentConfigResponse"> & {
  /**
   * Full .env.agent content (raw text, all KEY=VALUE pairs)
   *
   * @generated from field: string env = 1;
   */
  env: string;

  /**
   * Full agent.toml content (raw text, if available)
   *
   * @generated from field: string agent_toml = 2;
   */
  agentToml: string;
};

/**
 * Describes the message silvana.ledger.v1.GetAgentConfigResponse.
 * Use `create(GetAgentConfigResponseSchema)` to create a new message.
 */
export const GetAgentConfigResponseSchema: GenMessage<GetAgentConfigResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 1);

/**
 * @generated from message silvana.ledger.v1.RegisterAgentRequest
 */
export type RegisterAgentRequest = Message<"silvana.ledger.v1.RegisterAgentRequest"> & {
  /**
   * Base58 Ed25519 public key (agent identity)
   *
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * @generated from field: optional string invite_code = 2;
   */
  inviteCode?: string | undefined;

  /**
   * @generated from field: optional string email = 3;
   */
  email?: string | undefined;

  /**
   * @generated from field: optional string agent_name = 4;
   */
  agentName?: string | undefined;

  /**
   * Ed25519 message-level signature proving ownership of public_key
   *
   * @generated from field: silvana.ledger.v1.MessageSignature request_signature = 30;
   */
  requestSignature?: MessageSignature | undefined;
};

/**
 * Describes the message silvana.ledger.v1.RegisterAgentRequest.
 * Use `create(RegisterAgentRequestSchema)` to create a new message.
 */
export const RegisterAgentRequestSchema: GenMessage<RegisterAgentRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 2);

/**
 * @generated from message silvana.ledger.v1.RegisterAgentResponse
 */
export type RegisterAgentResponse = Message<"silvana.ledger.v1.RegisterAgentResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: uint64 waiting_list_id = 3;
   */
  waitingListId: bigint;

  /**
   * @generated from field: silvana.ledger.v1.OnboardingStatus status = 4;
   */
  status: OnboardingStatus;
};

/**
 * Describes the message silvana.ledger.v1.RegisterAgentResponse.
 * Use `create(RegisterAgentResponseSchema)` to create a new message.
 */
export const RegisterAgentResponseSchema: GenMessage<RegisterAgentResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 3);

/**
 * @generated from message silvana.ledger.v1.GetOnboardingStatusRequest
 */
export type GetOnboardingStatusRequest = Message<"silvana.ledger.v1.GetOnboardingStatusRequest"> & {
  /**
   * Base58 Ed25519 public key
   *
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * Ed25519 message-level signature proving ownership of public_key
   *
   * @generated from field: silvana.ledger.v1.MessageSignature request_signature = 30;
   */
  requestSignature?: MessageSignature | undefined;
};

/**
 * Describes the message silvana.ledger.v1.GetOnboardingStatusRequest.
 * Use `create(GetOnboardingStatusRequestSchema)` to create a new message.
 */
export const GetOnboardingStatusRequestSchema: GenMessage<GetOnboardingStatusRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 4);

/**
 * @generated from message silvana.ledger.v1.GetOnboardingStatusResponse
 */
export type GetOnboardingStatusResponse = Message<"silvana.ledger.v1.GetOnboardingStatusResponse"> & {
  /**
   * @generated from field: silvana.ledger.v1.OnboardingStatus status = 1;
   */
  status: OnboardingStatus;

  /**
   * Set when status >= TOPOLOGY_CREATED
   *
   * @generated from field: optional string party_id = 2;
   */
  partyId?: string | undefined;

  /**
   * Base64 multihash (set when SIGNATURE_REQUIRED)
   *
   * @generated from field: optional string multihash = 3;
   */
  multihash?: string | undefined;

  /**
   * @generated from field: optional string error_message = 4;
   */
  errorMessage?: string | undefined;

  /**
   * @generated from field: uint64 waiting_list_id = 5;
   */
  waitingListId: bigint;
};

/**
 * Describes the message silvana.ledger.v1.GetOnboardingStatusResponse.
 * Use `create(GetOnboardingStatusResponseSchema)` to create a new message.
 */
export const GetOnboardingStatusResponseSchema: GenMessage<GetOnboardingStatusResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 5);

/**
 * @generated from message silvana.ledger.v1.SubmitOnboardingSignatureRequest
 */
export type SubmitOnboardingSignatureRequest = Message<"silvana.ledger.v1.SubmitOnboardingSignatureRequest"> & {
  /**
   * Base58 Ed25519 public key
   *
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * Base64 Ed25519 signature of the multihash
   *
   * @generated from field: string multihash_signature = 2;
   */
  multihashSignature: string;

  /**
   * Ed25519 message-level signature proving ownership of public_key
   *
   * @generated from field: silvana.ledger.v1.MessageSignature request_signature = 30;
   */
  requestSignature?: MessageSignature | undefined;
};

/**
 * Describes the message silvana.ledger.v1.SubmitOnboardingSignatureRequest.
 * Use `create(SubmitOnboardingSignatureRequestSchema)` to create a new message.
 */
export const SubmitOnboardingSignatureRequestSchema: GenMessage<SubmitOnboardingSignatureRequest> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 6);

/**
 * @generated from message silvana.ledger.v1.SubmitOnboardingSignatureResponse
 */
export type SubmitOnboardingSignatureResponse = Message<"silvana.ledger.v1.SubmitOnboardingSignatureResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * Updated status after submission
   *
   * @generated from field: silvana.ledger.v1.OnboardingStatus status = 3;
   */
  status: OnboardingStatus;
};

/**
 * Describes the message silvana.ledger.v1.SubmitOnboardingSignatureResponse.
 * Use `create(SubmitOnboardingSignatureResponseSchema)` to create a new message.
 */
export const SubmitOnboardingSignatureResponseSchema: GenMessage<SubmitOnboardingSignatureResponse> = /*@__PURE__*/
  messageDesc(file_silvana_ledger_v1_onboarding, 7);

/**
 * Onboarding status progression for cloud agent waiting list
 *
 * @generated from enum silvana.ledger.v1.OnboardingStatus
 */
export enum OnboardingStatus {
  /**
   * @generated from enum value: ONBOARDING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Agent registered, waiting for backend
   *
   * @generated from enum value: ONBOARDING_STATUS_REQUESTED = 1;
   */
  REQUESTED = 1,

  /**
   * Backend created multihash; agent must sign
   *
   * @generated from enum value: ONBOARDING_STATUS_SIGNATURE_REQUIRED = 2;
   */
  SIGNATURE_REQUIRED = 2,

  /**
   * Backend created topology tx; agent can complete onboarding
   *
   * @generated from enum value: ONBOARDING_STATUS_TOPOLOGY_CREATED = 3;
   */
  TOPOLOGY_CREATED = 3,

  /**
   * Agent completed ledger onboarding
   *
   * @generated from enum value: ONBOARDING_STATUS_ONBOARDED = 4;
   */
  ONBOARDED = 4,
}

/**
 * Describes the enum silvana.ledger.v1.OnboardingStatus.
 */
export const OnboardingStatusSchema: GenEnum<OnboardingStatus> = /*@__PURE__*/
  enumDesc(file_silvana_ledger_v1_onboarding, 0);

